### PR TITLE
Faster update max quantities using NOWAIT

### PR DESCRIPTION
**Pull request by ghost**
Demonstration of the small improvement on example benchmark problem nthmp/BP09 with openmp. Add the DEVOLVE_TIMER flag to make BP09 to track the update_max_quantities time.

On an NCI node with two Cascade Lakes processors (48 cores) using 48 threads took: the run takes 1m25s with the update_max_quantities taking a total of 1.02s over all domains. Without the NOWAIT (the original), it takes 1m30s but update_max_quantities takes a total of 7.17s.

### CODE REVIEW

**Comment by gareth-d-ga** [comment]
Thanks Matt. That timing difference is interesting, noting the improved performance is better than on my machine with 16 cores (where the improvement was consistent, but marginal).

Do you have the evolve timing info for each case? I didn't find it in NCI. Were you definitely comparing the openmp runs in both cases?

I suspect the difference is that here you are using 48 cores over 2 CPUs -- which is probably inefficient (too many cores for the problem, and slow to synchronize between CPUs). So the overheads of synchronisation are larger, and NOWAIT improves this. 

It highlights the potential for improving scaleability with openmp, if we have other easy NOWAIT's available, or other ways to avoid a barrier.

Please check whether all the unit/parallel/validation tests PASS on NCI, and add a comment here about that.

**Comment by ghost** [comment]
The most recent timing available at on NCI at ptha_mm/propagation/SWALS/examples/nthmp/BP09/OUTPUTS/openmp_results/RUN_ID*/Evolve_timer_details.txt.

All unit tests, parallel tests and validation tests on NCI using ifx (intel-compiler-llvm/2024.0.2).

**Comment by gareth-d-ga** [comment]
> The most recent timing available at on NCI at ptha_mm/propagation/SWALS/examples/nthmp/BP09/OUTPUTS/openmp_results/RUN_ID*/Evolve_timer_details.txt.

But that's only one model -- to see the speedup I need the other model as well.

> All unit tests, parallel tests and validation tests on NCI using ifx (intel-compiler-llvm/2024.0.2).

Great, thanks

**Comment by gareth-d-ga** [comment]
For additional context, here are the Evolve timer results for this change on my home machine yesterday (16 cores, single CPU).
* BP09 was modified to store more summary statistics, to try to accentuate any differences.
* Stats below show the version with NOWAIT is marginally faster in the `update_max_quantities` calls -- much less dramatic than the results above.


# Before NOWAIT update
<details>
<summary>Click to expand</summary>

```
gareth@gareth-D3:~/Code_Experiments/fortran/Structured_shallow_water/examples/nthmp/BP09/OUTPUTS/RUN_20241016_111346422$ for i in */Evolve*.txt; do echo $i; cat $i; done
RUN_ID00000000010000000001_00001_20241016_111346.423/Evolve_timer_details.txt
############################################
WALLCLOCK TIME SUMMARY
--------------------------------------------
Details
                   nesting_boundary_flux_integral_tstep:           0.02662301 :   4.2423661115315214 %
                                        LF_update_stage:           0.14076924 :  22.4315242858005846 %
                                        boundary_update:           0.03812442 :   6.0751124628029629 %
                                          apply_forcing:           0.00019409 :   0.0309273843219518 %
                           LF_boundary_flux_integration:           0.03912701 :   6.2348746451621562 %
                                         LF_update_UHVH:           0.09084396 :  14.4759507445209099 %
                                  update_max_quantities:           0.29186920 :  46.5092443658599137 %
---------------
Total WALLCLOCK time:           0.62755093
############################################
RUN_ID00000000010000000002_00001_20241016_111346.426/Evolve_timer_details.txt
############################################
WALLCLOCK TIME SUMMARY
--------------------------------------------
Details
                                                 backup:           0.78557344 :   7.8557502580999001 %
                             compute_depth_and_velocity:           1.11070438 :  11.1070661917625912 %
                                         compute_fluxes:           4.16647968 :  41.6648807969626702 %
                                               update_U:           2.07034119 :  20.7034536673177989 %
                                        boundary_update:           0.00032838 :   0.0032838153664980 %
                                          apply_forcing:           0.00038782 :   0.0038782173182796 %
                   nesting_boundary_flux_integral_tstep:           0.31740486 :   3.1740550198249267 %
                                            rk2_average:           0.46053339 :   4.6053431751208418 %
                                  update_max_quantities:           1.08822669 :  10.8822888582265005 %
---------------
Total WALLCLOCK time:           9.99997984
############################################
RUN_ID00000000010000000003_00001_20241016_111346.427/Evolve_timer_details.txt
############################################
WALLCLOCK TIME SUMMARY
--------------------------------------------
Details
                                                 backup:           1.03014976 :   6.3979066788169012 %
                             compute_depth_and_velocity:           1.46216139 :   9.0809826686787432 %
                                         compute_fluxes:           6.85847674 :  42.5956455380610777 %
                                               update_U:           4.18997011 :  26.0224665874259138 %
                                        boundary_update:           0.00058971 :   0.0036625045277751 %
                                          apply_forcing:           0.00071173 :   0.0044202919306964 %
                   nesting_boundary_flux_integral_tstep:           0.63472649 :   3.9420684128491867 %
                                            rk2_average:           0.50891151 :   3.1606747389229799 %
                                  update_max_quantities:           1.41565905 :   8.7921725787867295 %
---------------
Total WALLCLOCK time:          16.10135649
############################################
RUN_ID00000000010000000004_00001_20241016_111346.427/Evolve_timer_details.txt
############################################
WALLCLOCK TIME SUMMARY
--------------------------------------------
Details
                                                 backup:           0.74993604 :   2.9703394442189559 %
                             compute_depth_and_velocity:           1.76868694 :   7.0053981998499886 %
                                         compute_fluxes:          12.70055317 :  50.3042286248575792 %
                                               update_U:           6.96342805 :  27.5806787373677089 %
                                        boundary_update:           0.00169258 :   0.0067039504515523 %
                                          apply_forcing:           0.00200330 :   0.0079346368984822 %
                   nesting_boundary_flux_integral_tstep:           0.88634915 :   3.5106431559804752 %
                                            rk2_average:           0.44957487 :   1.7806717972543686 %
                                  update_max_quantities:           1.72526209 :   6.8334014531208949 %
---------------
Total WALLCLOCK time:          25.24748619
############################################
RUN_ID00000000010000000005_00001_20241016_111346.428/Evolve_timer_details.txt
############################################
WALLCLOCK TIME SUMMARY
--------------------------------------------
Details
                                                 backup:           0.60879965 :   2.7996512353520204 %
                             compute_depth_and_velocity:           1.41637372 :   6.5133947309916929 %
                                         compute_fluxes:          10.44622049 :  48.0384214959634690 %
                                               update_U:           6.94733026 :  31.9482801774334035 %
                                        boundary_update:           0.00190099 :   0.0087419929021095 %
                                          apply_forcing:           0.00204268 :   0.0093935573532814 %
                   nesting_boundary_flux_integral_tstep:           0.47174325 :   2.1693780147825907 %
                                            rk2_average:           0.35110679 :   1.6146142213710262 %
                                  update_max_quantities:           1.50003535 :   6.8981245738503976 %
---------------
Total WALLCLOCK time:          21.74555318
############################################
RUN_ID00000000010000000006_00001_20241016_111346.429/Evolve_timer_details.txt
############################################
WALLCLOCK TIME SUMMARY
--------------------------------------------
Details
                                                 backup:           0.68858241 :   6.6340545153142312 %
                             compute_depth_and_velocity:           1.02417180 :   9.8672453783043430 %
                                         compute_fluxes:           4.52184564 :  43.5651133081661115 %
                                               update_U:           2.63009051 :  25.3392531012148225 %
                                        boundary_update:           0.00056761 :   0.0054685700005498 %
                                          apply_forcing:           0.00062964 :   0.0060661904565451 %
                   nesting_boundary_flux_integral_tstep:           0.29672051 :   2.8587138029303434 %
                                            rk2_average:           0.28851062 :   2.7796167326505805 %
                                  update_max_quantities:           0.92839206 :   8.9444684009624762 %
---------------
Total WALLCLOCK time:          10.37951080
############################################
```
</Details>


# After NOWAIT update

<Details>
<summary>Click to expand</summary>

```
gareth@gareth-D3:~/Code_Experiments/fortran/Structured_shallow_water/examples/nthmp/BP09/OUTPUTS/RUN_20241016_112836641$ for i in */Evolve*.txt; do echo $i; cat $i; done
RUN_ID00000000010000000001_00001_20241016_112836.642/Evolve_timer_details.txt
############################################
WALLCLOCK TIME SUMMARY
--------------------------------------------
Details
                   nesting_boundary_flux_integral_tstep:           0.02752200 :   4.5494100159248116 %
                                        LF_update_stage:           0.14146545 :  23.3843562491025274 %
                                        boundary_update:           0.03874602 :   6.4047496146464802 %
                                          apply_forcing:           0.00022611 :   0.0373768324863307 %
                           LF_boundary_flux_integration:           0.04210247 :   6.9595724239595604 %
                                         LF_update_UHVH:           0.09058770 :  14.9742219556401217 %
                                  update_max_quantities:           0.26430789 :  43.6903129082401662 %
---------------
Total WALLCLOCK time:           0.60495765
############################################
RUN_ID00000000010000000002_00001_20241016_112836.644/Evolve_timer_details.txt
############################################
WALLCLOCK TIME SUMMARY
--------------------------------------------
Details
                                                 backup:           0.79491557 :   7.8886835639975770 %
                             compute_depth_and_velocity:           1.11684471 :  11.0834846268321048 %
                                         compute_fluxes:           4.17379686 :  41.4204525048077556 %
                                               update_U:           2.11464110 :  20.9855424903894772 %
                                        boundary_update:           0.00031753 :   0.0031511864807263 %
                                          apply_forcing:           0.00039347 :   0.0039047582779717 %
                   nesting_boundary_flux_integral_tstep:           0.32220864 :   3.1975748218296207 %
                                            rk2_average:           0.47067643 :   4.6709582390839870 %
                                  update_max_quantities:           1.08286251 :  10.7462478083007724 %
---------------
Total WALLCLOCK time:          10.07665684
############################################
RUN_ID00000000010000000003_00001_20241016_112836.645/Evolve_timer_details.txt
############################################
WALLCLOCK TIME SUMMARY
--------------------------------------------
Details
                                                 backup:           1.02904559 :   6.4122918512641620 %
                             compute_depth_and_velocity:           1.45261127 :   9.0516566546102961 %
                                         compute_fluxes:           6.85978289 :  42.7453654358918200 %
                                               update_U:           4.19525890 :  26.1419170054586623 %
                                        boundary_update:           0.00084158 :   0.0052441309993962 %
                                          apply_forcing:           0.00070922 :   0.0044193698802615 %
                   nesting_boundary_flux_integral_tstep:           0.64680426 :   4.0304314026665216 %
                                            rk2_average:           0.48402765 :   3.0161215484075377 %
                                  update_max_quantities:           1.37893418 :   8.5925526008213389 %
---------------
Total WALLCLOCK time:          16.04801555
############################################
RUN_ID00000000010000000004_00001_20241016_112836.645/Evolve_timer_details.txt
############################################
WALLCLOCK TIME SUMMARY
--------------------------------------------
Details
                                                 backup:           0.73848751 :   2.9270725463366247 %
                             compute_depth_and_velocity:           1.76224568 :   6.9848452205194329 %
                                         compute_fluxes:          12.76195421 :  50.5833413081651315 %
                                               update_U:           6.94217920 :  27.5160538728692359 %
                                        boundary_update:           0.00158332 :   0.0062756380832496 %
                                          apply_forcing:           0.00208085 :   0.0082476751369150 %
                   nesting_boundary_flux_integral_tstep:           0.89636355 :   3.5528307437110271 %
                                            rk2_average:           0.46698997 :   1.8509636261034008 %
                                  update_max_quantities:           1.65767525 :   6.5703693690749807 %
---------------
Total WALLCLOCK time:          25.22955954
############################################
RUN_ID00000000010000000005_00001_20241016_112836.646/Evolve_timer_details.txt
############################################
WALLCLOCK TIME SUMMARY
--------------------------------------------
Details
                                                 backup:           0.60882393 :   2.7873528159902823 %
                             compute_depth_and_velocity:           1.41341162 :   6.4709625689636754 %
                                         compute_fluxes:          10.59223648 :  48.4939877019386003 %
                                               update_U:           7.00532748 :  32.0721941003199120 %
                                        boundary_update:           0.00178952 :   0.0081929023058830 %
                                          apply_forcing:           0.00178224 :   0.0081595751328888 %
                   nesting_boundary_flux_integral_tstep:           0.45766819 :   2.0953229003742737 %
                                            rk2_average:           0.35055566 :   1.6049341092089338 %
                                  update_max_quantities:           1.41077541 :   6.4588933257655414 %
---------------
Total WALLCLOCK time:          21.84237054
############################################
RUN_ID00000000010000000006_00001_20241016_112836.646/Evolve_timer_details.txt
############################################
WALLCLOCK TIME SUMMARY
--------------------------------------------
Details
                                                 backup:           0.69781403 :   6.6278030571372577 %
                             compute_depth_and_velocity:           1.05328929 :  10.0040894669910294 %
                                         compute_fluxes:           4.56413097 :  43.3498897269675041 %
                                               update_U:           2.73760500 :  26.0016365940488718 %
                                        boundary_update:           0.00053713 :   0.0051016439235638 %
                                          apply_forcing:           0.00065186 :   0.0061913057934554 %
                   nesting_boundary_flux_integral_tstep:           0.29548058 :   2.8064599402486530 %
                                            rk2_average:           0.28888403 :   2.7438061789853925 %
                                  update_max_quantities:           0.89019438 :   8.4550220859042682 %
---------------
Total WALLCLOCK time:          10.52858727
############################################

```
</Details>

**Comment by ghost** [comment]
The results of the evolve timer are below for one and two cascade lakes CPUs on NCI. Only the line with update_max_quantities are shown.

# Using 48 threads on 2 Cascade lakes CPUS (24 cores each. 48 cores total)

## With NOWAIT
```
update_max_quantities:           0.11152411 :  14.9288561807499516 %
update_max_quantities:           0.14983273 :   1.5170936529236070 %
update_max_quantities:           0.23244858 :   1.3181878200235022 %
update_max_quantities:           0.49302626 :   1.3871461536397542 %
update_max_quantities:           0.43365812 :   1.5213948519220979 %
update_max_quantities:           0.17146587 :   1.5165463988591676 %
```
**Totalling  1.53 seconds**


## Original
```
update_max_quantities:           0.52720428 :  50.3622085119398832 %
update_max_quantities:           0.41463065 :   8.6800162531287537 %
update_max_quantities:           0.80468893 :   9.7762751352152382 %
update_max_quantities:           2.27008915 :  13.2828868509569986 %
update_max_quantities:           2.32767177 :  15.9781675507472816 %
update_max_quantities:           0.77818060 :  14.3665670432987511 %
```
**Totalling 7.12 seconds**

# Using 24 threads on 1 cascade lake cpu (24 cores)
## With NOWAIT
```
update_max_quantities:           0.10040998 :  19.9957363952788896 %
update_max_quantities:           0.15944338 :   2.7262800985637616 %
update_max_quantities:           0.19077873 :   1.9087289216546526 %
update_max_quantities:           0.35133982 :   1.8493088135742495 %
update_max_quantities:           0.31546521 :   1.9385092558107977 %
update_max_quantities:           0.15878534 :   2.4922536429049598 %
```
**Totalling  1.28 seconds**

## Original
```
update_max_quantities:           0.36639762 :  47.7200446899063309 %
update_max_quantities:           0.35819292 :   5.9860615693707704 %
update_max_quantities:           0.57209611 :   5.5316430559805614 %
update_max_quantities:           1.46821642 :   7.3958245111173246 %
update_max_quantities:           1.43839574 :   8.3675849541142444 %
update_max_quantities:           0.53696203 :   8.0523198317472886 %
```
**Totalling 4.74 seconds**

The speed up is more significant over two CPUs (5.6 seconds), but still 3.5 seconds on a single CPU.

**Comment by gareth-d-ga** [comment]
Very interesting,

I guess this must reflect hardware differences between NCI and my machine.

It will be interesting to see if we get speedups on production models. And whether there are any other opportunities for NOWAITS or equivalent that can improve the speed further.

Happy for you to merge this

**Pull request merged**
